In [1]:
# To Import NumPy
import numpy as np

In [3]:
# Empty Array
np.empty(0)

array([], dtype=float64)

In [5]:
# Array with 2 elements
np.empty(2)

array([1.12756537e+93, 2.22525176e+88])

In [6]:
# Array with 3 Rows and 3 Columns
np.empty(shape=(3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.22920193e-321],
       [2.48273508e-312, 0.00000000e+000, 3.23815565e-319]])

In [7]:
np.empty(shape=(3,3),dtype=int)

array([[-1831674824,         117, -1796183304],
       [        117, -1796183304,         117],
       [          0,           1,      286718]])

In [8]:
np.empty(shape=(3,3),dtype=str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [9]:
a = np.empty(shape=(2,3),dtype=int)

In [10]:
a

array([[  856,     0,     0],
       [  117, 65541,     0]])

In [11]:
np.empty_like(a)

array([[  856,     0,     0],
       [  117, 65541,     0]])

In [12]:
#'eye' or I or Identity Matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
np.eye(3,3,dtype=str)

array([['1', '', ''],
       ['', '1', ''],
       ['', '', '1']], dtype='<U1')

In [16]:
#In the below code 3,3 represents Rows and Columns, k represents diagonal value index
np.eye(3,3,k=0,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
np.eye(3,3,k=-1,dtype=int)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [19]:
np.eye(3,3,k=1,dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [22]:
np.ones(5,dtype=str)

array(['1', '1', '1', '1', '1'], dtype='<U1')

In [23]:
np.ones(shape=(3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
#Two elements with 3 Rows and 3 Columns of int datatype
np.ones(shape=(2,3,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [27]:
np.ones(shape=(2,3,3),dtype=str)

array([[['1', '1', '1'],
        ['1', '1', '1'],
        ['1', '1', '1']],

       [['1', '1', '1'],
        ['1', '1', '1'],
        ['1', '1', '1']]], dtype='<U1')

In [28]:
a = np.ones(shape=(2,3,3),dtype=int)

In [29]:
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [30]:
np.ones_like(a)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros(shape=(2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
np.zeros(shape=(2,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [35]:
np.zeros(shape=(2,3,3),dtype=str)

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U1')

In [36]:
a = np.zeros(shape=(3,3,3),dtype=int)

In [37]:
a

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [39]:
np.zeros_like(a)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [43]:
np.full(2,fill_value=1)

array([1, 1])

In [44]:
np.full(shape=(3,3),fill_value=10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [45]:
np.full(shape=(3,3),fill_value="Hai")

array([['Hai', 'Hai', 'Hai'],
       ['Hai', 'Hai', 'Hai'],
       ['Hai', 'Hai', 'Hai']], dtype='<U3')

In [46]:
a = np.full(shape=(3,1),fill_value='Hello')

In [47]:
a

array([['Hello'],
       ['Hello'],
       ['Hello']], dtype='<U5')

In [48]:
np.full_like(a,'Hey')

array([['Hey'],
       ['Hey'],
       ['Hey']], dtype='<U5')

In [51]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [53]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [55]:
#np.linspace(start,end,how many divisions with equivalent distance you want)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [59]:
#Below code Excludes end point
np.linspace(0,10,5,endpoint=False)

array([0., 2., 4., 6., 8.])

In [61]:
#default base value=10, Below code gives 5 values in range of 1(10**1) to 100(10**2) 
np.logspace(1,2,5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [62]:
#Below code excludes endpoint
np.logspace(1,2,5,endpoint=False)

array([10.        , 15.84893192, 25.11886432, 39.81071706, 63.09573445])

In [63]:
#We can change default base value from 10 to ant no.as follows
np.logspace(1,2,5,base=5)
#Here the values ranging from 5(5**1) to 25(5**2)

array([ 5.        ,  7.47674391, 11.18033989, 16.71850762, 25.        ])

In [64]:
#rand  which gives value in the interval [0,1)
np.random.rand(10)

array([0.75738499, 0.18056714, 0.04574991, 0.7990039 , 0.71319657,
       0.61476342, 0.45157983, 0.16197982, 0.17482988, 0.41483667])

In [65]:
np.random.rand(3,3)

array([[0.53151251, 0.59050958, 0.78402716],
       [0.48192216, 0.66398368, 0.893467  ],
       [0.85602588, 0.27992872, 0.54601214]])

In [70]:
#randn Standard Normal Distribution random values
np.random.randn(1)

array([-0.83213153])

In [76]:
np.random.randn()

1.220425791374027

In [80]:
np.random.randint(5)

2

In [81]:
#random value in range
np.random.randint(5,15)

11

In [83]:
#To get random value between 1 to 6 for 10 times
np.random.randint(1,7,size=10)

array([4, 1, 5, 5, 1, 4, 5, 4, 6, 2])

In [87]:
a = np.arange(10)

In [88]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
#shuffle values in 'a'
np.random.shuffle(a)

In [90]:
a

array([5, 1, 8, 9, 7, 0, 3, 2, 4, 6])

In [93]:
#Reshape array of 12 elements to 4 Rows and 3 Columns
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])